name: Python Build (Linux/Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    env:
      BUILD_NAME: PyActionSandbox
      BUILD_ARGS: -F -w --add-data "res;res" src/main.py
      FILENAME: ${{ env.BUILD_NAME }}_${{ env.TARGET }}
      CMD_EXEC: ""
      CMD_EXTRAS: ""
      TARGET: ""
      FILE_TYPE: ""
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - if: ${{ runner.os == 'windows' || runner.os == 'linux' }}
      env:
        CMD_EXEC: PyInstaller
        TARGET: Windows
        FILE_TYPE: "exe"
      if: ${{ runner.os == 'linux' }}
        env:
          CMD_EXEC: pyinstaller
          CMD_EXTRAS: "&& cd dist/ && zip -r9 ${{ env.FILENAME }} ${{ env.FILENAME }}"
          TARGET: Linux
          FILE_TYPE: "zip"
      name: Build Project for ${{ matrix.os }} & Upload Artifact
      run: ${{ env.CMD_EXEC }} ${{ env.BUILD_ARGS }} -n ${{ env.FILENAME }} ${{ env.CMD_EXTRAS }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BUILD_NAME }}_${{ env.TARGET }}
        path: ${{ env.BUILD_NAME }}_${{ env.TARGET }}.${{ env.FILE_TYPE }}
