name: Python Build (Linux/Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            BUILD_NAME: PyActionSandbox_Windows
            BUILD_ARGS: -F -w --add-data "res;res" src/main.py
            CMD_EXEC: PyInstaller
            CMD_EXTRAS: ""
            FILE_TYPE: "exe"
          - os: ubuntu-latest
            BUILD_NAME: PyActionSandbox_Linux
            BUILD_ARGS: -F -w --add-data "res:res" src/main.py
            CMD_EXEC: pyinstaller
            CMD_EXTRAS: "&& cd dist/ && zip -r9 PyActionSandbox_Linux PyActionSandbox_Linux"
            FILE_TYPE: "zip"
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Project for ${{ matrix.os }}
      run: ${{ matrix.CMD_EXEC }} ${{ matrix.BUILD_ARGS }} -n ${{ matrix.BUILD_NAME }} ${{ matrix.CMD_EXTRAS }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.BUILD_NAME }}
        path: ${{ matrix.BUILD_NAME }}.${{ matrix.FILE_TYPE }}
